// <auto-generated />
using System;
using Common.Api.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Common.Api.Repositories.Migrations
{
    [DbContext(typeof(SticosWidgetDbContext))]
    [Migration("20180906100107_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Common")
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Api.Repositories.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DashboardConfig")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("DateCreated");

                    b.Property<bool>("IsDefault");

                    b.Property<int?>("OwnerId");

                    b.Property<int?>("OwnerTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("OwnerTypeId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("Common.Api.Repositories.Models.OwnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("OwnerTypes");
                });

            modelBuilder.Entity("Common.Api.Repositories.Models.Dashboard", b =>
                {
                    b.HasOne("Common.Api.Repositories.Models.OwnerType", "OwnerType")
                        .WithMany("Dashboards")
                        .HasForeignKey("OwnerTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
