//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace Altinn.Api.Domain.Schemas
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlRoot("melding", Namespace = "", IsNullable = false)]
    public partial class OppgiPersonalleder_M
    {

        private Skjemainnhold skjemainnholdField;

        private string dataFormatProviderField;

        private string dataFormatIdField;

        private string dataFormatVersionField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public OppgiPersonalleder_M()
        {
            this.dataFormatProviderField = "SERES";
            this.dataFormatIdField = "5363";
        }

        /// <remarks/>
        public Skjemainnhold Skjemainnhold
        {
            get
            {
                return this.skjemainnholdField;
            }
            set
            {
                this.skjemainnholdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string dataFormatProvider
        {
            get
            {
                return this.dataFormatProviderField;
            }
            set
            {
                this.dataFormatProviderField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string dataFormatId
        {
            get
            {
                return this.dataFormatIdField;
            }
            set
            {
                this.dataFormatIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string dataFormatVersion
        {
            get
            {
                return this.dataFormatVersionField;
            }
            set
            {
                this.dataFormatVersionField = value;
            }
        }

        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Skjemainnhold
    {

        private NaermesteLeder naermesteLederField;

        private Sykmeldt sykmeldtField;

        private string hendelseIdField;

        private string organisasjonsnummerField;

        private System.Nullable<bool> utbetalesLonnField;

        private bool utbetalesLonnFieldSpecified;

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public NaermesteLeder naermesteLeder
        {
            get
            {
                return this.naermesteLederField;
            }
            set
            {
                this.naermesteLederField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public Sykmeldt sykmeldt
        {
            get
            {
                return this.sykmeldtField;
            }
            set
            {
                this.sykmeldtField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "integer", IsNullable = true)]
        public string hendelseId
        {
            get
            {
                return this.hendelseIdField;
            }
            set
            {
                this.hendelseIdField = value;
            }
        }

        /// <remarks/>
        public string organisasjonsnummer
        {
            get
            {
                return this.organisasjonsnummerField;
            }
            set
            {
                this.organisasjonsnummerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public System.Nullable<bool> utbetalesLonn
        {
            get
            {
                return this.utbetalesLonnField;
            }
            set
            {
                this.utbetalesLonnField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool utbetalesLonnSpecified
        {
            get
            {
                return this.utbetalesLonnFieldSpecified;
            }
            set
            {
                this.utbetalesLonnFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NaermesteLeder
    {

        private string naermesteLederEtternavnField;

        private string naermesteLederFornavnField;

        private string naermesteLederFoedselsnummerField;

        private string naermesteLederMobilnummerField;

        private string naermesteLederEpostField;

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string naermesteLederEtternavn
        {
            get
            {
                return this.naermesteLederEtternavnField;
            }
            set
            {
                this.naermesteLederEtternavnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string naermesteLederFornavn
        {
            get
            {
                return this.naermesteLederFornavnField;
            }
            set
            {
                this.naermesteLederFornavnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string naermesteLederFoedselsnummer
        {
            get
            {
                return this.naermesteLederFoedselsnummerField;
            }
            set
            {
                this.naermesteLederFoedselsnummerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string naermesteLederMobilnummer
        {
            get
            {
                return this.naermesteLederMobilnummerField;
            }
            set
            {
                this.naermesteLederMobilnummerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string naermesteLederEpost
        {
            get
            {
                return this.naermesteLederEpostField;
            }
            set
            {
                this.naermesteLederEpostField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sykmeldt
    {

        private string sykmeldtNavnField;

        private string sykmeldtFoedselsnummerField;

        /// <remarks/>
        public string sykmeldtNavn
        {
            get
            {
                return this.sykmeldtNavnField;
            }
            set
            {
                this.sykmeldtNavnField = value;
            }
        }

        /// <remarks/>
        public string sykmeldtFoedselsnummer
        {
            get
            {
                return this.sykmeldtFoedselsnummerField;
            }
            set
            {
                this.sykmeldtFoedselsnummerField = value;
            }
        }
    }
}
