//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace Altinn.Api.Domain.Schemas
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    [XmlRoot("sykmeldingArbeidsgiver", Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "", IsNullable = false)]
    public partial class SykmeldingArbeidsgiver
    {

        private Sykmelding sykmeldingField;

        private string juridiskOrganisasjonsnummerField;

        private string virksomhetsnummerField;

        private string sykmeldingIdField;

        private System.DateTime mottattidspunktField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sykmelding sykmelding
        {
            get
            {
                return this.sykmeldingField;
            }
            set
            {
                this.sykmeldingField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string juridiskOrganisasjonsnummer
        {
            get
            {
                return this.juridiskOrganisasjonsnummerField;
            }
            set
            {
                this.juridiskOrganisasjonsnummerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string virksomhetsnummer
        {
            get
            {
                return this.virksomhetsnummerField;
            }
            set
            {
                this.virksomhetsnummerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sykmeldingId
        {
            get
            {
                return this.sykmeldingIdField;
            }
            set
            {
                this.sykmeldingIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime mottattidspunkt
        {
            get
            {
                return this.mottattidspunktField;
            }
            set
            {
                this.mottattidspunktField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Sykmelding
    {

        private System.DateTime syketilfelleFomField;

        private Pasient pasientField;

        private Arbeidsgiver arbeidsgiverField;

        private Periode[] perioderField;

        private Prognose prognoseField;

        private Tiltak tiltakField;

        private string meldingTilArbeidsgiverField;

        private KontaktMedPasient kontaktMedPasientField;

        private Behandler behandlerField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime syketilfelleFom
        {
            get
            {
                return this.syketilfelleFomField;
            }
            set
            {
                this.syketilfelleFomField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pasient pasient
        {
            get
            {
                return this.pasientField;
            }
            set
            {
                this.pasientField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Arbeidsgiver arbeidsgiver
        {
            get
            {
                return this.arbeidsgiverField;
            }
            set
            {
                this.arbeidsgiverField = value;
            }
        }

        /// <remarks/>
        [XmlElement("perioder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Periode[] perioder
        {
            get
            {
                return this.perioderField;
            }
            set
            {
                this.perioderField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Prognose prognose
        {
            get
            {
                return this.prognoseField;
            }
            set
            {
                this.prognoseField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Tiltak tiltak
        {
            get
            {
                return this.tiltakField;
            }
            set
            {
                this.tiltakField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string meldingTilArbeidsgiver
        {
            get
            {
                return this.meldingTilArbeidsgiverField;
            }
            set
            {
                this.meldingTilArbeidsgiverField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KontaktMedPasient kontaktMedPasient
        {
            get
            {
                return this.kontaktMedPasientField;
            }
            set
            {
                this.kontaktMedPasientField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Behandler behandler
        {
            get
            {
                return this.behandlerField;
            }
            set
            {
                this.behandlerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Pasient
    {

        private Navn navnField;

        private string identField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Navn navn
        {
            get
            {
                return this.navnField;
            }
            set
            {
                this.navnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ident
        {
            get
            {
                return this.identField;
            }
            set
            {
                this.identField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Navn
    {

        private string etternavnField;

        private string mellomnavnField;

        private string fornavnField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etternavn
        {
            get
            {
                return this.etternavnField;
            }
            set
            {
                this.etternavnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mellomnavn
        {
            get
            {
                return this.mellomnavnField;
            }
            set
            {
                this.mellomnavnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fornavn
        {
            get
            {
                return this.fornavnField;
            }
            set
            {
                this.fornavnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Behandler
    {

        private Navn navnField;

        private string telefonnummerField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Navn navn
        {
            get
            {
                return this.navnField;
            }
            set
            {
                this.navnField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefonnummer
        {
            get
            {
                return this.telefonnummerField;
            }
            set
            {
                this.telefonnummerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class KontaktMedPasient
    {

        private System.DateTime behandletField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime behandlet
        {
            get
            {
                return this.behandletField;
            }
            set
            {
                this.behandletField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Tiltak
    {

        private string tiltakArbeidsplassenField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tiltakArbeidsplassen
        {
            get
            {
                return this.tiltakArbeidsplassenField;
            }
            set
            {
                this.tiltakArbeidsplassenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Arbeidsutsikter
    {

        private bool harEgetArbeidPaaSiktField;

        private bool harEgetArbeidPaaSiktFieldSpecified;

        private System.DateTime arbeidFomField;

        private bool arbeidFomFieldSpecified;

        private bool harAnnetArbeidPaaSiktField;

        private bool harAnnetArbeidPaaSiktFieldSpecified;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool harEgetArbeidPaaSikt
        {
            get
            {
                return this.harEgetArbeidPaaSiktField;
            }
            set
            {
                this.harEgetArbeidPaaSiktField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool harEgetArbeidPaaSiktSpecified
        {
            get
            {
                return this.harEgetArbeidPaaSiktFieldSpecified;
            }
            set
            {
                this.harEgetArbeidPaaSiktFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime arbeidFom
        {
            get
            {
                return this.arbeidFomField;
            }
            set
            {
                this.arbeidFomField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool arbeidFomSpecified
        {
            get
            {
                return this.arbeidFomFieldSpecified;
            }
            set
            {
                this.arbeidFomFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool harAnnetArbeidPaaSikt
        {
            get
            {
                return this.harAnnetArbeidPaaSiktField;
            }
            set
            {
                this.harAnnetArbeidPaaSiktField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool harAnnetArbeidPaaSiktSpecified
        {
            get
            {
                return this.harAnnetArbeidPaaSiktFieldSpecified;
            }
            set
            {
                this.harAnnetArbeidPaaSiktFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Prognose
    {

        private bool erArbeidsfoerEtterEndtPeriodeField;

        private bool erArbeidsfoerEtterEndtPeriodeFieldSpecified;

        private string beskrivHensynArbeidsplassenField;

        private Arbeidsutsikter arbeidsutsikterField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool erArbeidsfoerEtterEndtPeriode
        {
            get
            {
                return this.erArbeidsfoerEtterEndtPeriodeField;
            }
            set
            {
                this.erArbeidsfoerEtterEndtPeriodeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool erArbeidsfoerEtterEndtPeriodeSpecified
        {
            get
            {
                return this.erArbeidsfoerEtterEndtPeriodeFieldSpecified;
            }
            set
            {
                this.erArbeidsfoerEtterEndtPeriodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beskrivHensynArbeidsplassen
        {
            get
            {
                return this.beskrivHensynArbeidsplassenField;
            }
            set
            {
                this.beskrivHensynArbeidsplassenField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Arbeidsutsikter arbeidsutsikter
        {
            get
            {
                return this.arbeidsutsikterField;
            }
            set
            {
                this.arbeidsutsikterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class AktivitetIkkeMulig
    {

        private bool manglendeTilretteleggingPaaArbeidsplassenField;

        private bool manglendeTilretteleggingPaaArbeidsplassenFieldSpecified;

        private string beskrivelseField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool manglendeTilretteleggingPaaArbeidsplassen
        {
            get
            {
                return this.manglendeTilretteleggingPaaArbeidsplassenField;
            }
            set
            {
                this.manglendeTilretteleggingPaaArbeidsplassenField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool manglendeTilretteleggingPaaArbeidsplassenSpecified
        {
            get
            {
                return this.manglendeTilretteleggingPaaArbeidsplassenFieldSpecified;
            }
            set
            {
                this.manglendeTilretteleggingPaaArbeidsplassenFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beskrivelse
        {
            get
            {
                return this.beskrivelseField;
            }
            set
            {
                this.beskrivelseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class GradertSykmelding
    {

        private int sykmeldingsgradField;

        private bool harReisetilskuddField;

        private bool harReisetilskuddFieldSpecified;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sykmeldingsgrad
        {
            get
            {
                return this.sykmeldingsgradField;
            }
            set
            {
                this.sykmeldingsgradField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool harReisetilskudd
        {
            get
            {
                return this.harReisetilskuddField;
            }
            set
            {
                this.harReisetilskuddField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool harReisetilskuddSpecified
        {
            get
            {
                return this.harReisetilskuddFieldSpecified;
            }
            set
            {
                this.harReisetilskuddFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Aktivitet
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("aktivitetIkkeMulig", typeof(AktivitetIkkeMulig), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("antallBehandlingsdagerUke", typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("avventendeSykmelding", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("gradertSykmelding", typeof(GradertSykmelding), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("harReisetilskudd", typeof(bool), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Periode
    {

        private System.DateTime fomField;

        private System.DateTime tomField;

        private Aktivitet aktivitetField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime fom
        {
            get
            {
                return this.fomField;
            }
            set
            {
                this.fomField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime tom
        {
            get
            {
                return this.tomField;
            }
            set
            {
                this.tomField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Aktivitet aktivitet
        {
            get
            {
                return this.aktivitetField;
            }
            set
            {
                this.aktivitetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://nav.no/melding/virksomhet/sykmeldingArbeidsgiver/v1/sykmeldingArbeidsgiver" +
        "")]
    public partial class Arbeidsgiver
    {

        private string navnField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string navn
        {
            get
            {
                return this.navnField;
            }
            set
            {
                this.navnField = value;
            }
        }
    }
}
