// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timereg.Api.Repositories.Context;

namespace Timereg.Api.Repositories.Migrations
{
    [DbContext(typeof(TimeregDbContext))]
    [Migration("20180926133240_ActionOnAbsenceExport")]
    partial class ActionOnAbsenceExport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Timereg")
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Timereg.Api.Repositories.Models.AbsenceExport", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AbsenceJson");

                    b.Property<int>("Action");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LocalAbsenceId");

                    b.Property<string>("Message");

                    b.Property<int>("Status");

                    b.Property<int>("UnitId");

                    b.HasKey("Id");

                    b.ToTable("AbsenceExports");
                });
#pragma warning restore 612, 618
        }
    }
}
