// <auto-generated />
using Integrations.Api.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Integrations.Api.Repositories.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20181009080735_isActiveFlag")]
    partial class isActiveFlag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Integrations")
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Integrations.Api.Repositories.Models.EntityMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted");

                    b.Property<int>("EntityId");

                    b.Property<string>("EntityName");

                    b.Property<string>("ExternalEntity");

                    b.Property<string>("ExternalPropertyName");

                    b.Property<string>("ExternalValue");

                    b.Property<bool>("Ignored");

                    b.Property<int>("IntegrationId");

                    b.HasKey("Id");

                    b.ToTable("EntityMaps");
                });

            modelBuilder.Entity("Integrations.Api.Repositories.Models.Integration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<int>("ExternalSystem");

                    b.Property<bool>("IsActivated");

                    b.Property<int>("UnitId");

                    b.HasKey("Id");

                    b.ToTable("Integrations");
                });
#pragma warning restore 612, 618
        }
    }
}
