// <auto-generated />
using Altinn.Api.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Altinn.Api.Repositories.Migrations
{
    [DbContext(typeof(AltinnDbContext))]
    partial class AltinnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Altinn")
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altinn.Api.Repositories.Models.NavMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("BusinessOrganizationNumber")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("IntegrationType");

                    b.Property<string>("MessageXml")
                        .IsRequired();

                    b.Property<string>("MesssageId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(255);

                    b.Property<string>("ReporteeId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("WorkState");

                    b.HasKey("Id");

                    b.ToTable("NavMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
